function model = prepare_TSE2D_sense_model( ...
        kspace,acquiredMask,calibrationMask,varargin)
%PREPARE_TSE2D_SENSE_MODEL Build a shared SENSE/CS encoding model.
%
% The model contains PCA-compressed k-space, the measured-line mask,
% single-set ESPIRiT (or low-resolution RSS) sensitivity maps, and map/
% compression diagnostics. Both recon_TSE2D_SENSE and recon_TSE2D_CS use
% this function so their data-consistency operator is identical.

    p = inputParser;
    p.addParameter('SensitivityMethod','espirit',@(x) ischar(x) || ...
        (isstring(x) && isscalar(x)));
    p.addParameter('SensitivityReadoutWidth',30,@(x) isnumeric(x) && ...
        isscalar(x) && isfinite(x) && x >= 2 && mod(x,1) == 0);
    p.addParameter('ESPIRiTKernelSize',[6 6],@(x) isnumeric(x) && ...
        isvector(x) && numel(x) == 2 && all(isfinite(x)) && ...
        all(x >= 2) && all(mod(x,1) == 0));
    p.addParameter('ESPIRiTSubspaceThreshold',0.02,@(x) isnumeric(x) && ...
        isscalar(x) && isfinite(x) && x > 0 && x < 1);
    p.addParameter('ESPIRiTEigenvalueCrop',0.95,@(x) isnumeric(x) && ...
        isscalar(x) && isfinite(x) && x >= 0 && x < 1.5);
    p.addParameter('CoilCompressionEnergy',0.99,@(x) isnumeric(x) && ...
        isscalar(x) && isfinite(x) && x > 0 && x <= 1);
    p.addParameter('MaximumVirtualCoils',12,@(x) isnumeric(x) && ...
        isscalar(x) && isfinite(x) && x >= 1 && mod(x,1) == 0);
    p.addParameter('MinimumVirtualCoils',4,@(x) isnumeric(x) && ...
        isscalar(x) && isfinite(x) && x >= 1 && mod(x,1) == 0);
    p.addParameter('SensitivityThreshold',0.02,@(x) isnumeric(x) && ...
        isscalar(x) && isfinite(x) && x >= 0 && x < 1);
    p.addParameter('SensitivityMaps',[],@(x) isempty(x) || isnumeric(x));
    p.addParameter('UseGPU','auto',@isValidUseGPU);
    p.addParameter('Verbose',true,@(x) islogical(x) && isscalar(x));
    p.parse(varargin{:});
    opt = p.Results;

    validateattributes(kspace,{'numeric'},{'nonempty'},mfilename,'kspace');
    if ndims(kspace) ~= 3
        error('prepare_TSE2D_sense_model:InvalidKspace', ...
            'KSPACE must have dimensions [readout, phase, coil].');
    end
    nPE = size(kspace,2);
    acquiredMask = logical(reshape(acquiredMask,1,[]));
    calibrationMask = logical(reshape(calibrationMask,1,[]));
    if numel(acquiredMask) ~= nPE || numel(calibrationMask) ~= nPE
        error('prepare_TSE2D_sense_model:MaskSize', ...
            'Sampling masks must match the phase-encoding dimension.');
    end
    acquiredMask = acquiredMask | calibrationMask;
    if nnz(acquiredMask) < 2 || nnz(calibrationMask) < 4
        error('prepare_TSE2D_sense_model:InsufficientSamples', ...
            'SENSE/CS requires measured data and at least four ACS lines.');
    end

    sensitivityMethod = lower(string(opt.SensitivityMethod));
    if ~ismember(sensitivityMethod,["espirit","rss"])
        error('prepare_TSE2D_sense_model:InvalidSensitivityMethod', ...
            'SensitivityMethod must be ''espirit'' or ''rss''.');
    end

    if isempty(opt.SensitivityMaps)
        [kspace,~,compressionInfo] = compress_TSE2D_coils( ...
            kspace,calibrationMask, ...
            'EnergyFraction',opt.CoilCompressionEnergy, ...
            'MaximumCoils',opt.MaximumVirtualCoils, ...
            'MinimumCoils',opt.MinimumVirtualCoils);
        switch sensitivityMethod
            case "espirit"
                [sensitivities,mapInfo] = estimate_TSE2D_espirit( ...
                    kspace,calibrationMask, ...
                    'CalibrationReadoutWidth',opt.SensitivityReadoutWidth, ...
                    'KernelSize',opt.ESPIRiTKernelSize, ...
                    'SubspaceThreshold',opt.ESPIRiTSubspaceThreshold, ...
                    'EigenvalueCrop',opt.ESPIRiTEigenvalueCrop, ...
                    'UseGPU',opt.UseGPU, ...
                    'Verbose',opt.Verbose);
            case "rss"
                [sensitivities,mapInfo] = estimate_TSE2D_sensitivities( ...
                    kspace,calibrationMask, ...
                    'ReadoutWidth',opt.SensitivityReadoutWidth, ...
                    'SupportThreshold',opt.SensitivityThreshold);
        end
    else
        sensitivities = opt.SensitivityMaps;
        if ~isequal(size(sensitivities),size(kspace))
            error('prepare_TSE2D_sense_model:SensitivitySize', ...
                'SensitivityMaps must match KSPACE dimensions.');
        end
        compressionMatrix = eye(size(kspace,3),'single');
        compressionInfo = struct('originalCoils',size(kspace,3), ...
            'virtualCoils',size(kspace,3),'energyFractionTarget',1, ...
            'retainedEnergyFraction',1,'eigenvalues',[], ...
            'compressionMatrix',compressionMatrix);
        mapInfo = struct('method','user supplied','supportMask', ...
            any(abs(sensitivities) > 0,3));
    end

    model = struct();
    model.kspace = complex(single(kspace));
    model.sensitivities = complex(single(sensitivities));
    model.acquiredMask = acquiredMask;
    model.calibrationMask = calibrationMask;
    model.mask = reshape(single(acquiredMask),1,nPE,1);
    model.compression = compressionInfo;
    model.sensitivity = mapInfo;
end

function tf = isValidUseGPU(value)
    tf = islogical(value) && isscalar(value);
    if tf
        return
    end
    tf = (ischar(value) || (isstring(value) && isscalar(value))) && ...
        strcmpi(string(value),'auto');
end
