function run_ci_tests
%RUN_CI_TESTS Execute repository tests and write CI artifacts.

root = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(fullfile(root,'pulseq')));
addpath(fullfile(root,'utils'), fullfile(root,'prep'), ...
    fullfile(root,'recon','matlab'), fullfile(root,'recon','matlab','utils'), fullfile(root,'tests'));

artifactDir = fullfile(root,'artifacts');
if ~exist(artifactDir,'dir')
    mkdir(artifactDir);
end

suite = testsuite(fullfile(root,'tests'), 'IncludeSubfolders', true);
runner = matlab.unittest.TestRunner.withTextOutput;

runner.addPlugin(matlab.unittest.plugins.XMLPlugin.producingJUnitFormat( ...
    fullfile(artifactDir,'junit.xml')));

% Report coverage for deterministic first-party modules exercised in CI.
% Scanner-side sequence execution, Twix/NIfTI I/O, experimental scripts, and
% vendored reconstruction packages require external data or dependencies and
% are intentionally validated outside this unit-test coverage scope.
coverageFiles = [ ...
    string(fullfile(root,'prep','prep_PE3DOrder.m')), ...
    string(fullfile(root,'prep','prep_PE3DOrder_PI.m')), ...
    string(fullfile(root,'prep','prep_SlicePositions.m')), ...
    string(fullfile(root,'prep','prep_SpoilingArea.m')), ...
    string(fullfile(root,'prep','prep_System.m')), ...
    string(fullfile(root,'utils','RoundRaster.m')), ...
    string(fullfile(root,'utils','design_gradient_waveform.m')), ...
    string(fullfile(root,'utils','design_gradient_min_time.m')), ...
    string(fullfile(root,'recon','matlab','apply_coil_matrix.m')), ...
    string(fullfile(root,'recon','matlab','apply_TSE_echomagcor.m')), ...
    string(fullfile(root,'recon','matlab','apply_TSE_phasecor.m')), ...
    string(fullfile(root,'recon','matlab','estimate_noise_whitener.m')), ...
    string(fullfile(root,'recon','matlab','pack_TSE2D_kspace.m')), ...
    string(fullfile(root,'recon','matlab','recon_TSE2D_RSS.m')), ...
    string(fullfile(root,'recon','matlab','utils','fft2c_TSE2D.m')), ...
    string(fullfile(root,'recon','matlab','utils','ifft2c_TSE2D.m')), ...
    string(fullfile(root,'recon','matlab','utils','sense_TSE2D_adjoint.m')), ...
    string(fullfile(root,'recon','matlab','utils','sense_TSE2D_forward.m'))];
coverageFormat = matlab.unittest.plugins.codecoverage.CoberturaFormat( ...
    fullfile(artifactDir,'coverage.xml'));
coveragePlugin = matlab.unittest.plugins.CodeCoveragePlugin.forFile( ...
    coverageFiles, 'Producing', coverageFormat);
runner.addPlugin(coveragePlugin);

results = runner.run(suite);
assertSuccess(results);
end
