function [...
    rfex, GSex ...
    ] = prep_Excitation(flipex, rfex_phase, SliceThickness, tEx, tExwd, dG, system)
    % Readout gradient
    [rfex, gz_ex]   = mr.makeSincPulse(flipex, system, 'Duration', tEx,...
        'SliceThickness', SliceThickness, 'apodization', 0.5, 'timeBwProduct', 4, 'PhaseOffset', rfex_phase,...
        'use', 'excitation');
    GSex         = mr.makeTrapezoid('z', system, 'amplitude', gz_ex.amplitude, 'FlatTime', tExwd, 'riseTime', dG);
    rfex.delay   = rfex.deadTime;
end
