%% Iterative 2-D TSE reconstruction: ordinary SENSE and CS
% This example reconstructs the same Siemens .dat file with the shared
% ESPIRiT-SENSE encoding model. SENSE uses CG with a small L2 term; CS adds
% isotropic TV and orthonormal Haar-L1 regularization.

clearvars;

%% User settings
exampleDir = fileparts(mfilename('fullpath'));
matlabDir = fileparts(exampleDir);
repoRoot = fileparts(fileparts(matlabDir));
addpath(matlabDir,fullfile(matlabDir,'utils'),exampleDir);
inputDat = fullfile(repoRoot,'Recon_dev','CS_Recon', ...
    'meas_MID00033_FID66698_CSTSE_0p4_300_r5_nRef30_sli5.dat');
mapVBVDPath = 'E:\Tools\mapVBVD';
outputDir = fullfile(fileparts(inputDat),'out');

% The supplied CS-TSE data has no phase-correction navigator. Do not enable
% navigator-derived phase or echo-magnitude correction for this file.
commonArguments = {'MapVBVDPath',mapVBVDPath, ...
    'Prewhiten',true, ...
    'PhaseCorrection',false, ...
    'EchoMagnitudeCorrection',false, ...
    'IterativeUseGPU','auto', ...
    'SensitivityMethod','espirit', ...
    'SensitivityReadoutWidth',30, ...
    'ESPIRiTKernelSize',[6 6], ...
    'ESPIRiTSubspaceThreshold',0.02, ...
    'ESPIRiTEigenvalueCrop',0.95, ...
    'CoilCompressionEnergy',0.99, ...
    'MaximumVirtualCoils',12, ...
    'KeepKspace',false, ...
    'OutputDir',outputDir, ...
    'SaveMat',true, ...
    'SaveFigures',true, ...
    'SaveNifti',true, ...
    'OverwriteOutputs',true, ...
    'Verbose',true};

%% Ordinary iterative SENSE
senseResult = recon_TSE2D(inputDat,commonArguments{:}, ...
    'ReconstructionMethod','sense', ...
    'SENSEIterations',50, ...
    'SENSETolerance',1e-5, ...
    'SENSETikhonov',1e-4, ...
    'OutputPrefix','CSTSE_R5_ESPIRiT_SENSE');

%% Parallel imaging + compressed sensing
csResult = recon_TSE2D(inputDat,commonArguments{:}, ...
    'ReconstructionMethod','cs', ...
    'CSIterations',250, ...
    'CSTVWeight',0.006, ...
    'CSWaveletWeight',0.0005, ...
    'CSWaveletLevels',2, ...
    'OutputPrefix','CSTSE_R5_ESPIRiT_CS');

fprintf('SENSE NIfTI: %s\n',senseResult.outputFiles.nifti);
fprintf('CS NIfTI:    %s\n',csResult.outputFiles.nifti);
