%% Offline reconstruction of a Siemens/Pulseq Cartesian 2D TSE Twix file
% Edit only the configuration block below for routine use. The processing
% functions live in this MATLAB reconstruction folder and do not support gSlider.

clear; clc;

exampleDir = fileparts(mfilename('fullpath'));
reconDir = fileparts(exampleDir);
addpath(reconDir,fullfile(reconDir,'utils'),exampleDir);

%% Configuration
twixFile = "F:\TSE_2D\dat\meas_MID01108_FID25068_TSE2D_1p0x1p0x2p0_120x120x5_0p0_5000_14p0_2_39.dat";
outputDir = "F:\TSE_2D\codex\ReconFlow";
mapVBVDPath = "E:\Tools\mapVBVD";

applyPrewhitening = true;
applyPhaseCorrection = true;

% Optional navigator-derived echo-envelope equalization. Keep disabled for
% an unmodified reconstruction; enable only when its effect has been
% evaluated for the target acquisition and reporting purpose.
applyEchoMagnitudeCorrection = false;
echoMagnitudeMethod = "wiener"; % "power" retains the legacy gain model.
echoMagnitudeAlpha = 0;         % 0 targets full equalization; 1 retains the envelope.
echoMagnitudeLambda = "auto";  % "auto" or a non-negative scalar.
echoMagnitudeMaxGain = 2;       % Smooth auto-Wiener gain limit, not a hard clip.

runGrappa = true;
comparePhaseCorrection = true;
slices = [];                    % [] reconstructs every acquired SLC.

%% Reconstruction
result = recon_TSE2D(twixFile, ...
    'MapVBVDPath',mapVBVDPath, ...
    'Prewhiten',applyPrewhitening, ...
    'NoiseShrinkage',0.02, ...
    'PhaseCorrection',applyPhaseCorrection, ...
    'EchoMagnitudeCorrection',applyEchoMagnitudeCorrection, ...
    'EchoMagnitudeMethod',echoMagnitudeMethod, ...
    'EchoMagnitudeAlpha',echoMagnitudeAlpha, ...
    'EchoMagnitudeLambda',echoMagnitudeLambda, ...
    'EchoMagnitudeMaxGain',echoMagnitudeMaxGain, ...
    'GRAPPA',runGrappa, ...
    'GrappaKySourceCount',4, ...
    'GrappaKxKernel',0, ...      % Fast and robust 1D PE-only diagnostic kernel.
    'GrappaRegularization',1e-4, ...
    'ComparePhaseCorrection',comparePhaseCorrection, ...
    'Slices',slices, ...
    'KeepKspace',false, ...
    'OutputDir',outputDir, ...
    'SaveMat',true, ...
    'SaveNifti',true, ...
    'SaveFigures',true, ...
    'Verbose',true);

% Main output used for display or downstream analysis:
imageTSE = result.images.reconstructed;
